name: Install, Enable, and Start Redis on Servers

on: [push]

jobs:
  install-enable-start-redis:
    runs-on: ubuntu-22.04
    env:
      server: ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
    - name: Install, Enable, Start Redis, and Restart Server
      run: |
        touch /home/runner/.ssh/known_hosts2
        chmod 600 /home/runner/.ssh/known_hosts2
        ssh -o UserKnownHostsFile=/home/runner/.ssh/known_hosts2 user@ubuntu
        ssh -vvv user@ubuntu
        echo "${SSH_PRIVATE_KEY}" > devpair.pem
        chmod 400 devpair.pem
        ssh -vvv -i devpair.pem user@${{ secrets.DEV_SERVER}} && user@${{ secrets.DEV_SERVER}}

        ssh -i devpair.pem -o StrictHostKeyChecking=no user@${{ secrets.DEV_SERVER}} '
          sudo apt update &&
          sudo apt install redis-server &&
          sudo systemctl enable redis-server &&
          sudo systemctl start redis-server &&
          sudo systemctl restart redis-server
        '

        ssh -i devpair.pem -o StrictHostKeyChecking=no user@${{ secrets.PROD_SERVER}} '
          sudo apt update &&
          sudo apt install redis-server &&
          sudo systemctl enable redis-server &&
          sudo systemctl start redis-server &&
          sudo systemctl restart redis-server
        '
