name: Install, Enable, and Start Redis on Servers

on: [push]

jobs:
  install-enable-start-redis:
    runs-on: ubuntu-22.04
    env:
      SSH_HOST: ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}

    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SERVER}}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
    
      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd

   
        
