name: Setup Redis  

on: [push]  

jobs:
  setup-redis:  
  
      runs-on: ${{ secrets.DEV_SERVER }}   
      env:
        SSH_HOST: ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
  

      steps: 
        - name: Install redis-server on Dev server
          run: |
            sudo apt update 
            sudo apt upgrade -y
            sudo apt-get install lsb-release curl gpg
            curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
            sudo chmod 644 /usr/share/keyrings/redis-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
            sudo apt-get update
            sudo apt-get install redis
            sudo systemctl enable redis-server
            sudo systemctl start redis-server
 
      
